config/routes.rb
Blog::Application.routes.draw do
  root :to => "statics#home"
  resources :statics
  resources :users
  get '/register', to: 'users#new'

  resources :sessions, only: [:new , :create, :destroy]
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'

  resources :images  do
    resources :comments
  end
  get '/articles' ,to: 'images#show'
  post '/images/add_comment' => "images#add_comment"
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :image
  attr_accessible :body, :commenter, :user_id
  belongs_to :user
end

app/models/image.rb
class Image < ActiveRecord::Base
  	attr_accessible :title, :content, :src
 	mount_uploader :src, PhotoUploader

 	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name ,:password, :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery
	include SessionsHelper

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  	@image=Image.new
  end
  def create
  	image = Image.new :title => params[:image][:title],
  	                  :content => params[:image][:content]
  	upload = PhotoUploader.new
  	upload.store! params[:image][:src]
  	image.src = upload
  	if image.save
  		redirect_to "/"
  	else
  		flash[:notice] = "errors"
  		render :new
  	end
  end

  def show
    @image=Image.find_by_src(params[:src].to_s.split('/').last)
    @comment = Comment.new
    @comments = @image.comments
  end

  def index
  end

  def add_comment
    if params[:img_id]
      img = Image.find(params[:img_id].to_i)
      img.comments.create params[:comment].merge({:user_id=>current_user.id})
      redirect_to params[:ref]
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    	@user = User.new
    end

    def create
    #   @user=User.new
    #   user=User.find_by_email(params[:user][:email])
    #     if user && user.authenticate(params[:user][:password])
    #         flash[:success]="欢迎登录！"
    #         redirect_to users_path
    #     else
    #         flash[:error]=@user.error.full_messagess
    #         render 'new'
    #     end
    	@user = User.where(params[:user]).first
    	puts "******************user=#{@user}"
        if @user.present?
        	session[:user_id] = @user.id
        	flash[:success]="欢迎登录！"       	

        else
	    	@user = User.new
        	session[:user_id] = nil
        	if session[:error_login_times].blank?
               session[:error_login_times] = 0
            else
                session[:error_login_times] += 1
        	end
    #       显示登录次数；
    #       puts "**************session[:error_login_times]=#{session[:error_login_times]}"
        	if session[:error_login_times]>2
        	    flash[:error]="请登录!！"
        	    session[:error_login_times] = 0
        	else
                flash[:error]="邮箱或密码错误！"
                return render 'new'
            end
    	end	 
        redirect_to :root
    end

    def destroy
    	session[:user_id] = @current_user = nil
    	redirect_to '/'
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	def home
		@images = Image.page(params[:page]).per(4)
	end

	def index		
	end

	def show		
	end
	def new
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users=User.page(params[:page]).per(2)	
	end
	def new
		@user=User.new
	end
	def show
		@user=User.find(params[:id])
	end
	def create
		user=User.new(params[:user])
		if user.save	
			session[:user_id] = user.id		
			redirect_to :root
		else
			# flash[:error]=@user.errors.full_messages
			render 'new'
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		if session[:user_id].present?
			@user ||= User.where(id: session[:user_id]).first
		end
	end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/new.html.erb
<h1>上传图片</h1>
<%= form_for @image ,:html => {:multipart => true} do |f| %>
<div class="field">
	<%= f.label ("标题:") %><br />
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label ("内容:") %><br />
	<%= f.text_area :content %>
</div>
<div class="field">
	<label>图片</label>
	<%= f.file_field :src %>
</div>
<div class="actions">
	<%= f.submit("上传") %>
</div>
<% end -%>

app/views/images/show.html.erb
<style>
body{
	background-color:#DDDDDD;
}	
div#conter{
	width:  982px;
	height: auto;
	margin: 30px auto;
	padding: auto ;
	background-color: #FFFFFF ;
}
div#tag{
   border-bottom: 2px solid #EDEDED;
   color: #777777;
   height: 40px;
   line-height: 45px;
   padding: 0 0 0 20px;
}
div#details{
	height: auto;
	margin: auto 10px auto;
	padding: 10px; 
  background-color: #ffffff;
  border-bottom: 1px solid #EDEDED;
}
div#details img{
	width:300px  ;
  border:medium none;
  vertical-align: middle;
   
}
div#details h1{
   border-bottom: 2px  #EDEDED;
   color: #777777;
   height: 50px;
   margin: 20px 20px 10px;
   line-height: 30px ;
   padding: 4px 20px 0 30px;
   text-align: center;
}
.article{
   margin:4px; 
   font-size: 20px;
   line-height: 1.5em;
   text-align: center;
   overflow:hidden;     /*防止内容超出容器或者产生自动换行*/
   overflow:auto;
}
div#comments{
	height: auto;
	margin: auto 10px auto;
	padding: 4px ; 
  background-color:#FFFFFF;
  border-bottom: 1px solid #DDDDDD;
}
div#post,#list,#comment{
	border-bottom: 2px solid #E5E5E5;
	color: #777777;
	height: auto;
	line-height: 35px;
	padding: 10px 0 0 25px;
	background-color: #ffffff;

}
div#totals{
   border-bottom: 2px solid #E5E5E5;
   color: #777777;
   height: 30px;
   line-height: 30px;
   padding: 0 0 0 25px;
}
div#comments p.title{
  border-bottom: 2px solid #E5E5E5;
  color: #777777;
  height: 35px;
  line-height: 35px;
  margin: 0px auto;
  padding: 10px 0 0 25px;
  background-color: #444444;
}
/*.textarea{
  border: 2px solid #CCCCCC;
  border-radius: 0 0 0 0;
  color: #666666;
  overflow: hidden;
  font-size: 16px;
  min-height: 60px;
  margin: 0 15px 10px 100px;
  overflow: hidden;
  padding: 30px 40px 20px 100px;
  background: none repeat scroll 0 0 #ffffff;
}
*/
div#comment textarea {
    background: none repeat scroll 0 0 transparent;
    border: 1px solid #CCCCCC;
    border-radius: 0 0 0 0;
    color: #666666;
    display: block;
    float: right;
    font-size: 16px;
    min-height: 60px;
    overflow: hidden;
    padding: 2px 8px;
    width: 590px;
}

.namebox{
	margin: 0px 0px  10px;
	padding: 15px 15px 10px ;
	height: 70px;
	width: 80px;
	font-size: 16px;
	float: left;
	color: black;
	background: repeat scroll 0 0 #666666;
}
/*.button{
  border: 0 none;
  cursor: pointer;
  height: 35px;
  width: 100px;
  background-color: #1E90FF;
}
*/
</style>    
<div id="conter">
	<div id="tag">
		个人图片页面
	</div>
	<div id="details">
        <h1><%= image_tag @image.title%></h1>
	    <p><%= image_tag @image.src  %></p>
	    <p class="article"><%= image_tag @image.content%></p>
	</div>
	<div id="comments">
			<p class="title">用户评论:</p>
		<div id="post">		       		
			<%= form_for @comment,:url=>"/images/add_comment",:method=>"post" do |f|  %>
			<div class="namebox">
				<%= current_user.name %>
			</div>
					<input type="hidden" value="<%=@image.id%>" name="img_id" />
					<input type="hidden" value="<%=request.url%>" name="ref" />
			    <%= f.text_area :commenter,{:placeholder => "说说我的看法..."} %>
					<%= f.submit("发表") %>
				<%end-%>
		</div>
		<div id="totals">
			<span>共有?条评论</span>
		</div>
		<div id="list">
			<% @comments.each do |comment| -%>
		      <div class="comment">		        	
				    <div ><%= comment.user.name %></div>
				    <div><%= comment.commenter %></div>
				  </div>
		  <% end -%>	
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<style>
.footline {
 width:1000px; height:auto;
 margin: 0px auto;
 overflow: hidden;
 zoom:1;
}
.footline div {
    float:left;
    margin-right: 10px;
}
</style>
<div class="footline">
    <div>
        <%= link_to "Ruby on rails ",:root, id: "logo" %>
    </div>
    <div>  
      <%= link_to "About",   '#' %></li>
      <%= link_to "Contact", '#' %></li>
      <a href="http://news.railstutorial.org/">News</a>
    </div>
    <div>
        <%= link_to "用户信息", users_path %>           
    </div>
</div>            

app/views/layouts/_header.html.erb
<style>
.headline {

 width:1000px; height:auto;
 margin: 0 auto;
 overflow: hidden;
 zoom:1;
}
.headline div {
    float:left;
    margin-right: 10px;
    
}
</style>
<div class="headline">
    <div>
        <%= link_to "Ruby on rails ",:root, id: "logo" %>
    </div>
    <div>     
        <% unless current_user.blank? %>
        欢迎 :
        <%= current_user.name %>
        <%= link_to "退出", logout_path %>
        <%= link_to"上传图片",new_image_path%>
        <% else %>
        <%= link_to "登录",  login_path %>
        <span><%= link_to "注册", register_path %></span>                
        <%  end  %>
    </div>
    <div>
        <span><%= link_to "用户信息", users_path %></span>            
    </div>
</div>            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header'%>

    <%= yield %>

    <%= render 'layouts/footer'%>
</body>
</html>

app/views/statics/home.html.erb
<style type ="text/css">
  div { list-style-type: none; }
  div#content{
    width: 1000px;
    margin: 70px 350px ;
    padding: 10px ;
    background-color: #444444; 
  }
  div#showleft{
    width: 500px;
    margin: 30px 0px 10px; 
    background-color: #888888;
    border-style: solid;
  }
  .itme{
    background: none repeat scroll 0 0 #000000;
    border-bottom: 1px solid #1F1F1F;
    height: 160px;
    overflow: hidden;
    padding: 10px;
  }
  .itme_left {
    color: #FFFFFF;
    width: 200px;
    max-width: 100%;
    padding: 30px;
    float: right;
  }
  img {
    width:200px  ;
    margin: 10px;
    max-width: 100%;
    border:medium none;

  }
  .paginate{
    clear: both;;
    background-color: #000000;
    margin: auto ;
    max-width: 100%;
    padding: 20px 0 15px 20px;
  }

</style>
  <div id="content">    
    <div id="showleft">
      <% if current_user.present? %>
        <div class="itmelist">                                       
          <% @images.each_with_index do |img| -%>
            <div class="itme">
              <div class="itme_left">                 
                <a>标题:<%= img.title%></a>
              </div>
              <div>
                <%= link_to image_tag(img.src.url), articles_path(src: img.src) %>
              </div>     
            </div>  
          <%end-%>           
        </div>                        
      <% else %>
        <div class="itmelist">                                       
          <% @images.each_with_index do |img| -%>
            <div class="itme">
              <div class="itme_left">           
                <a>标题:<%= img.title%></a>
              </div>
              <div>
                <%= link_to image_tag(img.src.url), articles_path(src: img.src) %>
              </div> 
            </div>
          <%end-%>              
        </div>
      <% end %>
      <div class="paginate">
        <%= paginate @images %>
      </div> 
    </div>         
  </div>

app/views/statics/new.html.erb
<!-- CSS:例1 -->
<!-- <html>
<head>
	<title></title>
	<style type="text/css">
	h1{
		color: green;
		text-decoration: underline;
	}
	em{
		color:red ;
	}
	li li{
		color: blue;
		font-weight: bold;
	}

	</style>
</head>
	<body>
		<h1>Web设计
			<em>sssssssssssssssss</em>
		</h1>
		<ul>
		    <li>HTML</li>
		    <li>CSS
		    <ul>
			   <li><%= link_to("选择器:") %></li>
			   <li>盒子模型</li>
			   <li>浮动与定位</li>
		   </ul>
		   </li>
		</ul>		
	</body>
</html> -->

<!--  CSS:例2 -->
<!-- <head>
	<style type="text/css">
	p{
		color: green;
	}
	.red{
		color: red;
	}
	.purple{
		color: purple;
	}
	#line3{
		color: blue;
	}

	</style>
</head>
<body>
	<p>这是第1行文本</p>
	<p class="red">这是第2行文本</p>
	<p id="line3"class="red">这是第3行文本</p>
	<p style="color:orange;"id="line3">这是第4行文本</p>
	<p class="purple red">这是第5行文本</p>
</body>
 -->


<!--  CSS:例3 -->

app/views/users/index.html.erb
<h1>All User</h1>
<p><%= flash[:success] -%></p>
<%= paginate @users %>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    | <%= link_to "Delete",user,method: :Delete , confirm: "确定删除？"%>
    </li>
<% end %>
</ul>
<%= paginate @users %>

app/views/users/new.html.erb
<html>	
<head>
	<title></title>
	<%=	stylesheet_link_tag"register.css"%>
</head>
<body>
	<h1 class="register-h1">新用户注册</h1>
	<ul>
		<li>请输入您的注册信息
		<ul>
			<li>注意：请务必输入有效的邮箱用于接收激活邮件</li>
			<li>注意：邮箱和密码必须大于6个字符</li>
		</ul>
		</li>
	</ul>
	<p><%= flash[:error].to_s -%></p>
	<%= form_for @user do |u| %>
	<p>
		<%=u.label ("用户名:") %>
		<%=u.text_field :name %>
	</p><br/>
	<p>
		<%=u.label ("邮箱:") %>
		<%=u.text_field :email %>
	</p><br/>
	<p>
		<%=u.label("密码:")%>
		<%=u.password_field :password %>
	</p><br/>
	<p><%= u.submit("注册！")%>  |<%= link_to "Sign in !",login_path%></p>
	<% end  %>
</body>	
</head>		
</html>	

app/views/users/show.html.erb
<h1>All Users</h1>
<p><%=@user.name%></p>
<p><%=@user.email%></p>
<p><%=@user.password%></p>